### ISSUE TITLE
Enigma integration support

### ISSUE THREAD

**Issue by NebelNidas** [QuiltMC/quiltflower#126]
Hi there! Thanks to SuperCoder's (*and others' 😉) hard work, Quiltflower has become one of, if not the best Java decompilers to date. That's why I asked in the Fabric Discord if there's a way of using it with Enigma, but apparently Fernflower (and its forks) don't provide the needed AST implementation:
![image](https://user-images.githubusercontent.com/48808497/167456442-df00a538-1a6f-4fe1-9181-373bcb53bbb5.png)

Since the Quilt toolchain houses both a decompiler and its own fork of Enigma now, I wanted to ask if it's possible to make them work together? Would make sense IMO to make in-house developed software compatible with each other, especially when it's this good.

**Comment by jaskarth** [comment]
This has since been fixed, with the addition of text tokens
