### ISSUE TITLE
Java code causes OutOfMemoryError while decompiling

### ISSUE THREAD

**Issue by Kroppeb** [QuiltMC/quiltflower#130]
[https://gist.github.com/Kroppeb/ce6552cc9038950360502773d6cc544b](https://gist.github.com/Kroppeb/ce6552cc9038950360502773d6cc544b)

**Comment by SuperCoder7979** [comment]
Another: https://gist.github.com/SuperCoder7979/178f44b3632db2e1b5ca8613c7484325

**Comment by SuperCoder7979** [comment]
Fixed by #159
