### ISSUE TITLE
JDK-19 adds `String::valueOf` calls to string concatenation

### ISSUE THREAD

**Issue by skyrising** [QuiltMC/quiltflower#151]
With https://github.com/openjdk/jdk/commit/cfee4512f7048e9cf440078e9eb87d37c7ebcdd9 extra `String::valueOf` calls are inserted for objects passed to `makeConcatWithConstants`. Quiltflower should remove these for better readability.

**Comment by thewindsofwinter** [comment]
Hi, I can probably write this up real quick. Let me know where I should look!

**Comment by SuperCoder7979** [comment]
Hey, thanks! I'd recommend that you look [here](https://github.com/QuiltMC/quiltflower/blob/develop/1.9.0/src/org/jetbrains/java/decompiler/modules/decompiler/ConcatenationHelper.java#L100), and just before the return insert a loop that goes over the `parameters` array and call, and runs the existing `removeStringValueOf` method over each exprent, to remove the valueOf call.

**Comment by thewindsofwinter** [comment]
Understood! Shouldn't be too difficult a fix, definitely will get it done within a few hours once I get a bit of free time. Question: how should we run tests before committing? Is there code style that I'll need to follow/recommended linting? Should I squash commits (probably unnecessary, my guess is I'll get it in one). Let me know, thanks!

**Comment by thewindsofwinter** [comment]
Just added a loop in extractParameters, hopefully what you wanted (since the only other place those parameters come up via a call to extractParameters). Let me know if that's what you want! Also, out of curiosity how does this integrate into the overall code? It's a little hard for a newcomer to understand 😅

**Comment by SuperCoder7979** [comment]
Fixed by #153
