### ISSUE TITLE
The file does not open

### ISSUE THREAD

**Issue by cog1233** [QuiltMC/quiltflower#177]
When I download the latest release and try and open it, it doesn't open.
Am I using the file wrong?

**Comment by SuperCoder7979** [comment]
How are you opening it? Double clicking?

**Comment by cog1233** [comment]
Yes

**Comment by SuperCoder7979** [comment]
The quiltflower jar is a command line application, so double clicking has no effect. You need to interact with it from the command line, or use a GUI tool like [shotav's decompiler](https://github.com/shotav/Decompiler) or [the Intellij IDEA plugin](https://plugins.jetbrains.com/plugin/18032-quiltflower).
