### ISSUE TITLE
Unnecessary casts causing the decompiled code to not be compilable

### ISSUE THREAD

**Issue by ByMartrixx** [QuiltMC/quiltflower#20]
I have noticed that there are many compiling errors on decompiled code related to casts, mainly with raw generics and null to Object casts.
Here are a few examples:

- `Optional.of((Comparable)property.getType().cast(comparable))` in `net.minecraft.state.State#getOrEmpty`
- `this.list.add((Object)null)` in `net.minecraft.util.collection.IdList#set`
- `(State)function.apply(object)` in `net.minecraft.state.StateManager#StateManager`
- `.orElse((Object)null)` in `net.minecraft.entity.Entity#getTeleportTarget`
- `(BlockPos)this.getSleepingPosition().orElse((Object)null)` in `net.minecraft.entity.LivingEntity#getSleepingDirection`
- `Supplier<ConfiguredFeature<?, ?>> supplier2 : (List)list.get(j)` in `net.minecraft.world.biome.Biome#generateFeatureStep`
- `((ChunkTickScheduler)this.blockTickScheduler).tick(this.world.getBlockTickScheduler(), pos -> this.getBlockState(pos).getBlock())` in `net.minecraft.world.chunk.WorldChunk#disableTickSchedulers`
- `this.charMap.put(c, (Object)null)` in `net.minecraft.block.pattern.BlockPatternBuilder#aisle`

**Comment by OroArmor** [comment]
There are hundreds. I'm trying to completely recompile minecraft so that all these issues can be found

**Comment by i509VCB** [comment]
Have you seen the `LiteralArgumentBuilder` casts hehahahahahh. It's crazy how many casts you get thee.

**Comment by jaskarth** [comment]
Closing this issue since it's pretty outdated, and most of these cases seem to be fixed now
