### ISSUE TITLE
Seemingly dangling file systems for input jars in 1.9.0

### ISSUE THREAD

**Issue by Juuxel** [QuiltMC/quiltflower#219]
## The bug

After [updating LQF to Quiltflower 1.9.0](https://github.com/Juuxel/LoomQuiltflower/compare/da503243fbdeb9bede9963ef8e8c3a688fb4a1d5...656b85c16ffaebfea4d5a04f0b0346e56df90348) (and fixing a compilation error due to a rename), the LQF tests are failing with `FileSystemException`s on Windows.

This only happens with the decompilation path using Loom's current decompilation API (Loom 0.11+), so the relevant code can be found in LQF's [`impl.modern.QuiltflowerDecompiler`](https://github.com/Juuxel/LoomQuiltflower/blob/85aa26b578e13785b4988b5d2d04187a02c6d1c1/src/loom011/java/juuxel/loomquiltflower/impl/modern/QuiltflowerDecompiler.java)

More specifically, when Loom tries to apply line mappings to the jar, it fails due to the compiled Minecraft jar "being in use by another process". This didn't happen in the [previous commit](https://github.com/Juuxel/LoomQuiltflower/commit/da503243fbdeb9bede9963ef8e8c3a688fb4a1d5) where all tests succeeded.

```
    Caused by: java.io.UncheckedIOException: Failed to remap line numbers
    	at net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction.doDecompile(GenerateSourcesTask.java:281)
    	at net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction.execute(GenerateSourcesTask.java:224)
    	... 22 more
    Caused by: java.nio.file.FileSystemException: D:\a\LoomQuiltflower\LoomQuiltflower\build\tmp\test\work\.gradle-test-kit\caches\fabric-loom\1.16.5\net.fabricmc.yarn.1_16_5.1.16.5+build.10-v2\minecraft-merged-named.jar: The process cannot access the file because it is being used by another process
    	at net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction.doDecompile(GenerateSourcesTask.java:278)
    	... 23 more
```

Note that since this has happened before in some specific setups, [I try to force-close any file systems pointing to the input jar](https://github.com/Juuxel/LoomQuiltflower/blob/85aa26b578e13785b4988b5d2d04187a02c6d1c1/src/loom011/java/juuxel/loomquiltflower/impl/modern/QuiltflowerDecompiler.java#L54-L65), but that doesn't seem to help with this crash.

## Replacing deprecations?

Avoiding using my own bytecode provider and the deprecated `Fernflower` constructor via reflection still didn't solve the issue: https://github.com/Juuxel/LoomQuiltflower/commit/85aa26b578e13785b4988b5d2d04187a02c6d1c1

https://github.com/QuiltMC/quiltflower/blob/2124e6e0062c1ce266981c4c5aa47e40acef08a8/src/org/jetbrains/java/decompiler/main/Fernflower.java#L31-L36

Even though the code should now run the upper constructor that doesn't use any of my code for reading the inputs, the tests still fail. This leads me to believe it's a QF regression.

**Comment by zml2008** [comment]
https://github.com/Juuxel/LoomQuiltflower/blob/85aa26b578e13785b4988b5d2d04187a02c6d1c1/src/loom011/java/juuxel/loomquiltflower/impl/modern/QuiltflowerDecompiler.java#L53

You don't clear the context here, so FF never releases its resources. See similar code in `ConsoleDecompiler`: https://github.com/QuiltMC/quiltflower/blob/2124e6e0062c1ce266981c4c5aa47e40acef08a8/src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java#L234-L241

**Comment by Juuxel** [comment]
Looks like it's something I inherited from Loom :eyes:

https://github.com/FabricMC/fabric-loom/blob/7173c2a6cb321d572c3212ad4a0e329ac2cef5c1/src/main/java/net/fabricmc/loom/decompilers/fernflower/FabricFernFlowerDecompiler.java#L63-L64

I'll test if adding `clearContext` fixes it.

**Comment by Juuxel** [comment]
`clearContext` fixed it, so it was a bug in LQF all along :smile:

Thanks @zml2008!
