### ISSUE TITLE
First local variable of a static method is marked as a parameter in the text token system

### ISSUE THREAD

**Issue by SpaceWalkerRS** [QuiltMC/quiltflower#229]
This leads to problems in Enigma where the first local variable will be considered renameable.

![Schermafbeelding 2022-12-09 om 01 24 28](https://user-images.githubusercontent.com/48224626/206595210-4f61985f-9ac0-4d84-bbcd-20af59412586.png)

**Comment by SpaceWalkerRS** [comment]
The issue might be [this](https://github.com/QuiltMC/quiltflower/blob/3fcb4c0ce4acfff4269ceec0bee6e21071ef78f9/src/org/jetbrains/java/decompiler/modules/decompiler/exps/VarExprent.java#L154) check. Instance methods have the first variable reserved for the `this` parameter, but static methods do not, so all the variable indices are 1 lower. This check does not take that into account.

**Comment by ByMartrixx** [comment]
Fixed by 912d592f98e0585ecd9d4bd18835799c9a6e4f45, will push a new version in enigma shortly to fix this issue
