### ISSUE TITLE
org.jetbrains.java.decompiler.struct.StructContext cannot be converted to java.lang.AutoCloseable

### ISSUE THREAD

**Issue by nbauma109** [QuiltMC/quiltflower#237]
Just got this error while upgrading from 1.8.1 to 1.9.0.
Why isn't StructContext Closeable anymore?

**Comment by SuperCoder7979** [comment]
The closeable interface was removed from StructContext as it doesn't handle the filesystems it has to close directly anymore. `StructContext#clear` handles clearing the context now.

**Comment by nbauma109** [comment]
Ok, thanks
