### ISSUE TITLE
Incorrect unmatched label introduced in switch statement in loop

### ISSUE THREAD

**Issue by DagSonntag** [QuiltMC/quiltflower#244]
I was trying to decompile spring-boot (spring-core-6.0.4.jar), using Quiltflower 1.9.0 and default settings, and got an incorrect parsing of spring-core-6.0.4\org\springframework\asm\ClassReader.java.

The decompiler added a "break label3;" on row 1221 and 1230, but with no label declared on the actual while loop in row 1006. Looking at the original source code I saw there was no label there, and that it also would not be needed to break the loop so not sure how it sneaked in. 

I tried to look if this was covered in a previous issue but could not find anything. I also only used the latest binary downloadable here, not building the decompiler myself using the latest sourcecode.

**Comment by SuperCoder7979** [comment]
This issue has been tracked internally, but there was no issue filed. Thanks for this, will look into!

**Comment by jaskarth** [comment]
Closing as it's been fixed.
