### ISSUE TITLE
Enum field references in switch cases are not tokenized

### ISSUE THREAD

**Issue by SpaceWalkerRS** [QuiltMC/quiltflower#246]
This leads to problems in Enigma where those references are not remapped properly.

![Schermafbeelding 2023-03-08 om 01 50 05](https://user-images.githubusercontent.com/48224626/223590903-4643c02a-d69c-45c7-816a-a5575d6c45f7.png)

**Comment by ByMartrixx** [comment]
Fixed in ed85b981f5a96cfcfe7f3dfd21fea07a5788e6c6. QuiltMC/enigma@7511de009550c9eb002801deb514d3f05545dfd8 updates Enigma to include this fix (not released yet)
