### ISSUE TITLE
Deploy releases to maven repo (https://mvnrepository.com/)

### ISSUE THREAD

**Issue by sdoeringNew** [QuiltMC/quiltflower#248]
I know of https://maven.quiltmc.org/repository/release/org/quiltmc/quiltflower/ but the number one source for deployed dependencies is Maven Central ~the Maven Repository https://mvnrepository.com/~.

Please deploy releases to this repository.

**Comment by zml2008** [comment]
mvnrepository.com is not a repository, it's an indexer. I believe the team has already begun plans to publish releases to maven central via OSSRH though, it's just a matter of ensuring the appropriate keys are configured in the appropriate places and it's set up in a way that's sustainable for the organization.

**Comment by sdoeringNew** [comment]
You are right. I meant Maven Central.

**Comment by jaskarth** [comment]
Hi, thank you for opening an issue, and sorry for the delay! The latest release version (1.9.0) is now [on Maven Central](https://repo1.maven.org/maven2/org/quiltmc/quiltflower/1.9.0/) for public use. Thanks!
