### ISSUE TITLE
Decompiled jar is corrupted

### ISSUE THREAD

**Issue by Crec0** [QuiltMC/quiltflower#42]
## Issue
Decompiled jar fails to extract using zip tools. Same error using 7zip, WinRar, python zipfile module, jar xf.
Not a permission error. Tried with elevated terminal or running as administrator 
The output produced by the command [output.txt](https://github.com/QuiltMC/quiltflower/files/7222475/output.txt).
The error from 7zip which I get when trying to extract [image](https://user-images.githubusercontent.com/83436716/134618570-04b503d6-5df2-4bbf-8acd-beb5085d81f3.png)
The jar's decompiled using [fernflower](https://github.com/fesh0r/fernflower) extract perfectly fine, therefore I believe it's a quiltflower issue on my machine. 

Running a windows 10 machine
JDK-16

## How to reproduce
* run command `java -jar quiltflower.jar -dgs=true src.jar dest` 
* Extract it with any of the zip tools mentioned

## Expected
* Jar is successfully extracted.

**Comment by skyrising** [comment]
This is probably fixed by 65d2a843e257e5adeda4dea231b2c2a7b56ed59a , can you test with a dev build?

**Comment by Crec0** [comment]
Tested build from develop/1.6.0 branch and it seems to have fixed the issue. Yesterday had the issue with compiling the development build because gradle build task was conflicting with JRE 8 installation. Had to remove JRE 8 for it to work. 
Thanks sky
