### ISSUE TITLE
NPE with infinite loop generated through 3 goto instructions

### ISSUE THREAD

**Issue by P03W** [QuiltMC/quiltflower#64]
Tested on Quiltflower 1.6.1, openjdk version 16.0.1, consistent as far as I can tell

Method contains valid bytecode that runs properly

.class and resulting .java:
[3_GOTO.zip](https://github.com/QuiltMC/quiltflower/files/7646466/3_GOTO.zip)

**Comment by SuperCoder7979** [comment]
Will be fixed in 1.7.0 :)
