### ISSUE TITLE
Can't decompile class files that are not in a jar

### ISSUE THREAD

**Issue by AirMCx** [QuiltMC/quiltflower#77]
It seems like we can't decompile the class files outside a jar.
For example, I extracted some of the class files into a folder and told QuiltFlower to decompile this folder and put the decompiled class into another folder. Even though in the log it seems like it decompiled correctly, there is nothing in the decompile folder. After that, I checked if decompiling a jar file will work. It did work.

**Comment by SuperCoder7979** [comment]
Can you try adding `--legacy-saving` before the input jar? so like `java -jar quiltflower-1.7.0.jar -dgs=1 -rsy=1 --legacy-saving ./inputdir/ ./output/`. That may fix that problem. It will be fixed in 1.8.0 as well

**Comment by Alvinn8** [comment]
I'm also having this issue, `--legacy-saving` did fix it.
