### ISSUE TITLE
Input jar FileSystems are not closed

### ISSUE THREAD

**Issue by Juuxel** [QuiltMC/quiltflower#78]
It seems that the input jar with bytecode isn't closed properly on Windows which leads to access issues. Here's one instance of it happening consistently in loom-quiltflower tests: https://github.com/Juuxel/LoomQuiltflower/runs/4928246300?check_suite_focus=true

**Comment by CoolMineman** [comment]
See #76 nothing is currently closed

**Comment by SuperCoder7979** [comment]
Should be fixed as the PR has been merged
