### ISSUE TITLE
Decompiling a folder of classes seems to not store classes anywhere?

### ISSUE THREAD

**Issue by KJP12** [QuiltMC/quiltflower#86]
## Expected behaviour
Running `java -jar quiltflower-1.7.0.jar ./classes ./src` would decompile classes found in `./classes` into the folder `./src`.

## Actual behaviour
It does attempt to decompile them, but it seems that the source files are never sent anywhere, not even in the working directory, input folders, tmp or the expected `./src` folder.

## Workarounds found
Jar the classes before attempting to decompile.

**Comment by SuperCoder7979** [comment]
Fixed with commit 0d9ee48 🙂
