### ISSUE TITLE
"Could not verify finally blocks" while decompiling NativeUtils library

### ISSUE THREAD

**Issue by wafflecoffee** [QuiltMC/quiltflower#87]
Using QF 1.7.0 via the IntelliJ plugin, default config there.

// $FF: Could not verify finally blocks. A semaphore variable has been added to preserve control flow.

[relevant source code](https://github.com/raman-rajarathinam/native-utils/blob/master/src/main/java/com/nativeutils/NativeUtils.java#L114-L127)
[class file](https://github.com/QuiltMC/quiltflower/files/8394361/NativeUtils.class.gz) (gzipped because GitHub wouldn't accept it otherwise)

**Comment by SuperCoder7979** [comment]
The issue has been fixed in dev. Thank you for the report!
