### ISSUE TITLE
Incorrect generated code in ScreenHandler#insertItem

### ISSUE THREAD

**Issue by BasiqueEvangelist** [QuiltMC/quiltflower#89]
The first `while` loop in `ScreenHandler#insertItem` is decompiled incorrectly.
Quiltflower generates this code:
![image](https://user-images.githubusercontent.com/72868417/161309574-bb98de87-1e47-4bb3-adc8-45a0686bde06.png)
Which is incorrect, as the while loop will continue if the if condition is false.

CFR generates code which matches the actual behaviour:  
![image](https://user-images.githubusercontent.com/72868417/161309674-e5ef7b5c-4ee8-4097-bb30-d98c40b3eca4.png)

**Comment by SuperCoder7979** [comment]
Hey, thanks for this report- seems like the ternary in if statement simplifier continues to cause problems. While not a permanent fix, the simplification step has been disabled by default in 1.8.0 as a stopgap measure.

**Comment by SuperCoder7979** [comment]
#104 fixes this properly, and Quiltflower now outputs the correct code. Thank you again for making this known!
