### ISSUE TITLE
No way to tell if decompiler has finished if input jar is empty or corrupt

### ISSUE THREAD

**Issue by TwilightFlower** [QuiltMC/quiltflower#9]
The only way right now to tell if the decompiler has finished is to wait for the `closeArchive` call. When there are no valid input files, this method never gets called, and your code indefinitely waits for the decompiler to finish.

**Comment by SuperCoder7979** [comment]
I looked into this and it seems like closeArchive is called every time for empty jars. Since I can't replicate it, I'm closing this for now but please reopen it if you can find a jar that exhibits this behavior
